{% set name = "scamp" %}
{% set version = "2.14.0" %}

package:
  name: astromatic-{{ name }}
  version: {{ version }}

source:
  url: https://github.com/astromatic/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: a5fc28c88860ff18ac1237841913c236116839bcdd9c77ca1b4a7f652e79d351
  patches:
    - 0001-Search-lapacke-library.patch
    - 0002-Fix_sprintf_buffer_overflow.patch

build:
  skip: true  # [win]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - autoconf
    - automake
    - libtool
    - make
  host:
    - fftw
    - curl
    - openblas
  run:
    - fftw
    - libcurl
    - openblas

test:
  commands:
    - scamp -d

about:
  home: http://www.astromatic.net/software/scamp
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: A utility that computes astrometric solutions from SExtractor catalogs
  description: |
    SCAMP (Software for Calibrating AstroMetry and Photometry) is a computer
    program that computes astrometric projection parameters from source
    catalogues derived from FITS images. The computed solution is expressed
    according to the WCS standard.
  doc_url: https://scamp.readthedocs.io/
  dev_url: https://github.com/astromatic/scamp

extra:
  recipe-maintainers:
    - drbixx
    - teake
